name: Deploy Next.js to GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build application
      run: npm run build
      env:
        NEXT_PUBLIC_SITE_URL: https://tarhunta.xyz
        NEXT_PUBLIC_BASE_URL: https://tarhunta.xyz
        WORDPRESS_API_URL: https://public-api.wordpress.com/rest/v1.1/sites/beyond2capi.wordpress.com/posts

    - name: Create CNAME file
      run: echo "tarhunta.xyz" > ./out/CNAME

    - name: Setup Pages
      uses: actions/configure-pages@v4
      with:
        static_site_generator: next

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./out

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
